import { z } from 'zod';
export declare const TargetPeriodSchema: z.ZodOptional<z.ZodNullable<z.ZodString>>;
export type TargetPeriod = z.infer<typeof TargetPeriodSchema>;
export declare function getTargetPeriodRange(period: string): {
    start: Date;
    end: Date;
};
export declare const TaskStatusSchema: z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>;
export type TaskStatus = z.infer<typeof TaskStatusSchema>;
export declare const PersonOrgSchema: z.ZodString;
export type PersonOrg = z.infer<typeof PersonOrgSchema>;
export declare const ProjectOrgSchema: z.ZodString;
export type ProjectOrg = z.infer<typeof ProjectOrgSchema>;
export declare const ProjectStatusSchema: z.ZodEnum<["active", "planning", "paused", "completed", "archived"]>;
export type ProjectStatus = z.infer<typeof ProjectStatusSchema>;
export declare const TaskPersonRoleSchema: z.ZodEnum<["assignee", "waiting_on", "stakeholder", "reviewer", "cc"]>;
export type TaskPersonRole = z.infer<typeof TaskPersonRoleSchema>;
export declare const UpdateTypeSchema: z.ZodEnum<["progress", "status_change", "blocker", "note", "attachment"]>;
export type UpdateType = z.infer<typeof UpdateTypeSchema>;
export declare const PersonSchema: z.ZodObject<{
    id: z.ZodNumber;
    name: z.ZodString;
    email: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    org: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    airtable_ya_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    airtable_sv_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    id: number;
    email?: string | null | undefined;
    org?: string | null | undefined;
    notes?: string | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    airtable_ya_id?: string | null | undefined;
    airtable_sv_id?: string | null | undefined;
}, {
    name: string;
    id: number;
    email?: string | null | undefined;
    org?: string | null | undefined;
    notes?: string | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    airtable_ya_id?: string | null | undefined;
    airtable_sv_id?: string | null | undefined;
}>;
export type Person = z.infer<typeof PersonSchema>;
export declare const CreatePersonSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    name: z.ZodString;
    email: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    org: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    airtable_ya_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    airtable_sv_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    name: string;
    email?: string | null | undefined;
    org?: string | null | undefined;
    notes?: string | null | undefined;
    airtable_ya_id?: string | null | undefined;
    airtable_sv_id?: string | null | undefined;
}, {
    name: string;
    email?: string | null | undefined;
    org?: string | null | undefined;
    notes?: string | null | undefined;
    airtable_ya_id?: string | null | undefined;
    airtable_sv_id?: string | null | undefined;
}>;
export type CreatePerson = z.infer<typeof CreatePersonSchema>;
export declare const UpdatePersonSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    org: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    airtable_ya_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    airtable_sv_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    email?: string | null | undefined;
    org?: string | null | undefined;
    notes?: string | null | undefined;
    airtable_ya_id?: string | null | undefined;
    airtable_sv_id?: string | null | undefined;
}, {
    name?: string | undefined;
    email?: string | null | undefined;
    org?: string | null | undefined;
    notes?: string | null | undefined;
    airtable_ya_id?: string | null | undefined;
    airtable_sv_id?: string | null | undefined;
}>;
export type UpdatePerson = z.infer<typeof UpdatePersonSchema>;
export declare const ProjectSchema: z.ZodObject<{
    id: z.ZodNumber;
    slug: z.ZodString;
    name: z.ZodString;
    org: z.ZodString;
    status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["active", "planning", "paused", "completed", "archived"]>>>;
    priority: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    parent_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    id: number;
    slug: string;
    org: string;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    priority?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    parent_id?: number | null | undefined;
}, {
    name: string;
    id: number;
    slug: string;
    org: string;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    priority?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    parent_id?: number | null | undefined;
}>;
export type Project = z.infer<typeof ProjectSchema>;
export declare const CreateProjectSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    slug: z.ZodString;
    name: z.ZodString;
    org: z.ZodString;
    status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["active", "planning", "paused", "completed", "archived"]>>>;
    priority: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    parent_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    name: string;
    slug: string;
    org: string;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    priority?: number | null | undefined;
    parent_id?: number | null | undefined;
}, {
    name: string;
    slug: string;
    org: string;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    priority?: number | null | undefined;
    parent_id?: number | null | undefined;
}>;
export type CreateProject = z.infer<typeof CreateProjectSchema>;
export declare const UpdateProjectSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    name: z.ZodOptional<z.ZodString>;
    slug: z.ZodOptional<z.ZodString>;
    org: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodEnum<["active", "planning", "paused", "completed", "archived"]>>>>;
    priority: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    parent_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
}, "strip", z.ZodTypeAny, {
    description?: string | null | undefined;
    name?: string | undefined;
    slug?: string | undefined;
    org?: string | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    priority?: number | null | undefined;
    parent_id?: number | null | undefined;
}, {
    description?: string | null | undefined;
    name?: string | undefined;
    slug?: string | undefined;
    org?: string | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    priority?: number | null | undefined;
    parent_id?: number | null | undefined;
}>;
export type UpdateProject = z.infer<typeof UpdateProjectSchema>;
export declare const WorkstreamSchema: z.ZodObject<{
    id: z.ZodNumber;
    project_id: z.ZodNumber;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    target_period: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["active", "planning", "paused", "completed", "archived"]>>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    id: number;
    project_id: number;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    target_period?: string | null | undefined;
}, {
    name: string;
    id: number;
    project_id: number;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    target_period?: string | null | undefined;
}>;
export type Workstream = z.infer<typeof WorkstreamSchema>;
export declare const CreateWorkstreamSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    project_id: z.ZodNumber;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    target_period: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["active", "planning", "paused", "completed", "archived"]>>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    name: string;
    project_id: number;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    target_period?: string | null | undefined;
}, {
    name: string;
    project_id: number;
    description?: string | null | undefined;
    status?: "completed" | "archived" | "active" | "planning" | "paused" | null | undefined;
    target_period?: string | null | undefined;
}>;
export type CreateWorkstream = z.infer<typeof CreateWorkstreamSchema>;
export declare const MeetingSchema: z.ZodObject<{
    id: z.ZodNumber;
    title: z.ZodString;
    date: z.ZodString;
    path: z.ZodString;
    location: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: number;
    title: string;
    date: string;
    path: string;
    notes?: string | null | undefined;
    location?: string | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}, {
    id: number;
    title: string;
    date: string;
    path: string;
    notes?: string | null | undefined;
    location?: string | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}>;
export type Meeting = z.infer<typeof MeetingSchema>;
export declare const CreateMeetingSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    title: z.ZodString;
    date: z.ZodString;
    path: z.ZodString;
    location: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    title: string;
    date: string;
    path: string;
    notes?: string | null | undefined;
    location?: string | null | undefined;
}, {
    title: string;
    date: string;
    path: string;
    notes?: string | null | undefined;
    location?: string | null | undefined;
}>;
export type CreateMeeting = z.infer<typeof CreateMeetingSchema>;
export declare const TaskSchema: z.ZodObject<{
    id: z.ZodNumber;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>;
    priority: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    due_date: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    checkin_by: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    target_period: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    owner_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    workstream_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    parent_task_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    blocked_by_task_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    source_meeting_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    due_meeting_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    metadata: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
    completed_at: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: number;
    status: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred";
    title: string;
    description?: string | null | undefined;
    priority?: number | null | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
    completed_at?: string | null | undefined;
}, {
    id: number;
    status: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred";
    title: string;
    description?: string | null | undefined;
    priority?: number | null | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
    completed_at?: string | null | undefined;
}>;
export type Task = z.infer<typeof TaskSchema>;
export declare const CreateTaskSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    priority: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    title: z.ZodString;
    metadata: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    due_date: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    owner_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    target_period: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    checkin_by: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    workstream_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    parent_task_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    blocked_by_task_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    source_meeting_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    due_meeting_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
} & {
    status: z.ZodDefault<z.ZodOptional<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>>>;
}, "strip", z.ZodTypeAny, {
    status: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred";
    title: string;
    description?: string | null | undefined;
    priority?: number | null | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
}, {
    title: string;
    description?: string | null | undefined;
    status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | undefined;
    priority?: number | null | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
}>;
export type CreateTask = z.infer<typeof CreateTaskSchema>;
export declare const UpdateTaskSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    priority: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    title: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>>>;
    project_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    due_date: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    owner_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    target_period: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    checkin_by: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    workstream_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    parent_task_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    blocked_by_task_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    source_meeting_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    due_meeting_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>>>>;
}, "strip", z.ZodTypeAny, {
    description?: string | null | undefined;
    status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | undefined;
    priority?: number | null | undefined;
    title?: string | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
}, {
    description?: string | null | undefined;
    status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | undefined;
    priority?: number | null | undefined;
    title?: string | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
}>;
export type UpdateTask = z.infer<typeof UpdateTaskSchema>;
export declare const TaskWithRelationsSchema: z.ZodObject<{
    id: z.ZodNumber;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>;
    priority: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    due_date: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    checkin_by: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    target_period: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    owner_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    workstream_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    parent_task_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    blocked_by_task_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    source_meeting_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    due_meeting_id: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    metadata: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
    completed_at: z.ZodOptional<z.ZodNullable<z.ZodString>>;
} & {
    owner_name: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    project_slug: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    project_name: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    project_org: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    workstream_name: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    source_meeting_title: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    source_meeting_path: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    due_meeting_title: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    blocked_by_task_title: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    subtask_count: z.ZodOptional<z.ZodNumber>;
    subtasks_complete: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    id: number;
    status: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred";
    title: string;
    description?: string | null | undefined;
    priority?: number | null | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
    completed_at?: string | null | undefined;
    owner_name?: string | null | undefined;
    project_slug?: string | null | undefined;
    project_name?: string | null | undefined;
    project_org?: string | null | undefined;
    workstream_name?: string | null | undefined;
    source_meeting_title?: string | null | undefined;
    source_meeting_path?: string | null | undefined;
    due_meeting_title?: string | null | undefined;
    blocked_by_task_title?: string | null | undefined;
    subtask_count?: number | undefined;
    subtasks_complete?: number | undefined;
}, {
    id: number;
    status: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred";
    title: string;
    description?: string | null | undefined;
    priority?: number | null | undefined;
    metadata?: Record<string, unknown> | null | undefined;
    project_id?: number | null | undefined;
    due_date?: string | null | undefined;
    owner_id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    target_period?: string | null | undefined;
    checkin_by?: string | null | undefined;
    workstream_id?: number | null | undefined;
    parent_task_id?: number | null | undefined;
    blocked_by_task_id?: number | null | undefined;
    source_meeting_id?: number | null | undefined;
    due_meeting_id?: number | null | undefined;
    completed_at?: string | null | undefined;
    owner_name?: string | null | undefined;
    project_slug?: string | null | undefined;
    project_name?: string | null | undefined;
    project_org?: string | null | undefined;
    workstream_name?: string | null | undefined;
    source_meeting_title?: string | null | undefined;
    source_meeting_path?: string | null | undefined;
    due_meeting_title?: string | null | undefined;
    blocked_by_task_title?: string | null | undefined;
    subtask_count?: number | undefined;
    subtasks_complete?: number | undefined;
}>;
export type TaskWithRelations = z.infer<typeof TaskWithRelationsSchema>;
export declare const TaskUpdateSchema: z.ZodObject<{
    id: z.ZodNumber;
    task_id: z.ZodNumber;
    note: z.ZodString;
    update_type: z.ZodOptional<z.ZodEnum<["progress", "status_change", "blocker", "note", "attachment"]>>;
    old_status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>>>;
    new_status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>>>;
    created_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: number;
    note: string;
    task_id: number;
    created_at?: string | undefined;
    update_type?: "note" | "blocker" | "progress" | "status_change" | "attachment" | undefined;
    old_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
    new_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
}, {
    id: number;
    note: string;
    task_id: number;
    created_at?: string | undefined;
    update_type?: "note" | "blocker" | "progress" | "status_change" | "attachment" | undefined;
    old_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
    new_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
}>;
export type TaskUpdate = z.infer<typeof TaskUpdateSchema>;
export declare const CreateTaskUpdateSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    task_id: z.ZodNumber;
    note: z.ZodString;
    update_type: z.ZodOptional<z.ZodEnum<["progress", "status_change", "blocker", "note", "attachment"]>>;
    old_status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>>>;
    new_status: z.ZodOptional<z.ZodNullable<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>>>;
    created_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at">, "strip", z.ZodTypeAny, {
    note: string;
    task_id: number;
    update_type?: "note" | "blocker" | "progress" | "status_change" | "attachment" | undefined;
    old_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
    new_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
}, {
    note: string;
    task_id: number;
    update_type?: "note" | "blocker" | "progress" | "status_change" | "attachment" | undefined;
    old_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
    new_status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | null | undefined;
}>;
export type CreateTaskUpdate = z.infer<typeof CreateTaskUpdateSchema>;
export declare const TaskAttachmentSchema: z.ZodObject<{
    id: z.ZodNumber;
    task_id: z.ZodNumber;
    path: z.ZodString;
    label: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    attachment_type: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: number;
    path: string;
    task_id: number;
    label?: string | null | undefined;
    created_at?: string | undefined;
    attachment_type?: string | null | undefined;
}, {
    id: number;
    path: string;
    task_id: number;
    label?: string | null | undefined;
    created_at?: string | undefined;
    attachment_type?: string | null | undefined;
}>;
export type TaskAttachment = z.infer<typeof TaskAttachmentSchema>;
export declare const CreateTaskAttachmentSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    task_id: z.ZodNumber;
    path: z.ZodString;
    label: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    attachment_type: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at">, "strip", z.ZodTypeAny, {
    path: string;
    task_id: number;
    label?: string | null | undefined;
    attachment_type?: string | null | undefined;
}, {
    path: string;
    task_id: number;
    label?: string | null | undefined;
    attachment_type?: string | null | undefined;
}>;
export type CreateTaskAttachment = z.infer<typeof CreateTaskAttachmentSchema>;
export declare const TaskPersonSchema: z.ZodObject<{
    task_id: z.ZodNumber;
    person_id: z.ZodNumber;
    role: z.ZodEnum<["assignee", "waiting_on", "stakeholder", "reviewer", "cc"]>;
    created_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    role: "assignee" | "waiting_on" | "stakeholder" | "reviewer" | "cc";
    task_id: number;
    person_id: number;
    created_at?: string | undefined;
}, {
    role: "assignee" | "waiting_on" | "stakeholder" | "reviewer" | "cc";
    task_id: number;
    person_id: number;
    created_at?: string | undefined;
}>;
export type TaskPerson = z.infer<typeof TaskPersonSchema>;
export declare const TaskQuerySchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodUnion<[z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>, z.ZodArray<z.ZodEnum<["pending", "in_progress", "complete", "blocked", "cancelled", "deferred", "active", "paused"]>, "many">]>>;
    owner_id: z.ZodOptional<z.ZodNumber>;
    owner_name: z.ZodOptional<z.ZodString>;
    project_id: z.ZodOptional<z.ZodNumber>;
    project_slug: z.ZodOptional<z.ZodString>;
    workstream_id: z.ZodOptional<z.ZodNumber>;
    parent_task_id: z.ZodOptional<z.ZodNumber>;
    source_meeting_id: z.ZodOptional<z.ZodNumber>;
    has_due_date: z.ZodOptional<z.ZodBoolean>;
    due_before: z.ZodOptional<z.ZodString>;
    due_after: z.ZodOptional<z.ZodString>;
    target_period: z.ZodOptional<z.ZodString>;
    search: z.ZodOptional<z.ZodString>;
    include_completed: z.ZodOptional<z.ZodBoolean>;
    limit: z.ZodOptional<z.ZodNumber>;
    offset: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    search?: string | undefined;
    status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | ("pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred")[] | undefined;
    limit?: number | undefined;
    project_id?: number | undefined;
    offset?: number | undefined;
    owner_id?: number | undefined;
    target_period?: string | undefined;
    workstream_id?: number | undefined;
    parent_task_id?: number | undefined;
    source_meeting_id?: number | undefined;
    owner_name?: string | undefined;
    project_slug?: string | undefined;
    has_due_date?: boolean | undefined;
    due_before?: string | undefined;
    due_after?: string | undefined;
    include_completed?: boolean | undefined;
}, {
    search?: string | undefined;
    status?: "pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred" | ("pending" | "in_progress" | "active" | "blocked" | "complete" | "cancelled" | "paused" | "deferred")[] | undefined;
    limit?: number | undefined;
    project_id?: number | undefined;
    offset?: number | undefined;
    owner_id?: number | undefined;
    target_period?: string | undefined;
    workstream_id?: number | undefined;
    parent_task_id?: number | undefined;
    source_meeting_id?: number | undefined;
    owner_name?: string | undefined;
    project_slug?: string | undefined;
    has_due_date?: boolean | undefined;
    due_before?: string | undefined;
    due_after?: string | undefined;
    include_completed?: boolean | undefined;
}>;
export type TaskQuery = z.infer<typeof TaskQuerySchema>;
export interface ApiResponse<T> {
    success: boolean;
    data?: T;
    error?: string;
    meta?: {
        total?: number;
        limit?: number;
        offset?: number;
    };
}
export declare function formatTaskId(id: number): string;
export declare function parseTaskId(taskId: string): number | null;
