#!/bin/bash
# Development startup script - starts all services and configures ports

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$(dirname "$SCRIPT_DIR")"
PACKAGES_DIR="$(dirname "$WEB_DIR")"
ROOT_DIR="$(dirname "$PACKAGES_DIR")"

cd "$WEB_DIR"

# Default ports
NEXT_PORT=${PORT:-3000}
TERMINAL_PORT=${TERMINAL_PORT:-3002}
TASK_SERVICE_PORT=${TASK_SERVICE_PORT:-3004}

# Find available ports, ensuring no duplicates
echo "Checking ports..."

# Find first available port starting from given port
find_next_available() {
    local port=$1
    shift
    local exclude="$@"
    while true; do
        local in_use=false
        # Check system
        if lsof -i :$port >/dev/null 2>&1; then
            in_use=true
        fi
        # Check already assigned
        for p in $exclude; do
            if [ "$port" = "$p" ]; then
                in_use=true
                break
            fi
        done
        if [ "$in_use" = "true" ]; then
            echo "Port $port in use, trying $((port + 1))..." >&2
            port=$((port + 1))
        else
            break
        fi
    done
    echo $port
}

# Assign ports sequentially, passing already-assigned ports as exclusions
NEXT_PORT=$(find_next_available $NEXT_PORT)
TERMINAL_PORT=$(find_next_available $TERMINAL_PORT $NEXT_PORT)
TASK_SERVICE_PORT=$(find_next_available $TASK_SERVICE_PORT $NEXT_PORT $TERMINAL_PORT)

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Knowledge Work - Development Servers"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Next.js App:      http://localhost:$NEXT_PORT"
echo "  Terminal Server:  http://localhost:$TERMINAL_PORT"
echo "  Task Service:     http://localhost:$TASK_SERVICE_PORT"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

# Read paths from server .env if it exists
SERVER_ENV="$PACKAGES_DIR/server/.env"
if [ -f "$SERVER_ENV" ]; then
    CONTENT_PATH=$(grep -E '^KNOWLEDGE_BASE_PATH=' "$SERVER_ENV" | cut -d'"' -f2)
    DATABASE_PATH=$(grep -E '^DATABASE_URL=' "$SERVER_ENV" | cut -d'"' -f2 | sed 's/^file://')
fi
# Fallback to defaults if not found
CONTENT_PATH=${CONTENT_PATH:-$ROOT_DIR/content}
DATABASE_PATH=${DATABASE_PATH:-$PACKAGES_DIR/server/data/items.db}

# Write .env.development.local with the ports
ENV_FILE="$WEB_DIR/.env.development.local"
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/dev-all.sh
# Do not commit this file

PORT=$NEXT_PORT
TERMINAL_PORT=$TERMINAL_PORT
NEXT_PUBLIC_TERMINAL_PORT=$TERMINAL_PORT
TASK_SERVICE_PORT=$TASK_SERVICE_PORT
NEXT_PUBLIC_TASK_SERVICE_URL=http://localhost:$TASK_SERVICE_PORT
CONTENT_PATH=$CONTENT_PATH
DATABASE_PATH=$DATABASE_PATH
KNOWLEDGE_BASE_PATH=$CONTENT_PATH
EOF

echo "Environment written to .env.development.local"
echo ""

# Kill a process and all its children (recursive)
kill_tree() {
    local pid=$1
    local signal=${2:-TERM}

    # Get all child processes
    local children=$(pgrep -P $pid 2>/dev/null)
    for child in $children; do
        kill_tree $child $signal
    done

    # Kill the process itself
    kill -$signal $pid 2>/dev/null || true
}

# Cleanup function
cleanup() {
    echo ""
    echo "Shutting down services..."

    # Kill each service and its process tree
    for pid in $TERMINAL_PID $TASK_PID $NEXT_PID; do
        if [ -n "$pid" ] && kill -0 $pid 2>/dev/null; then
            kill_tree $pid TERM
        fi
    done

    sleep 1

    # Force kill any remaining processes on our ports
    for port in $NEXT_PORT $TERMINAL_PORT $TASK_SERVICE_PORT; do
        lsof -ti :$port 2>/dev/null | xargs kill -9 2>/dev/null || true
    done

    wait 2>/dev/null
    echo "All services stopped."
}

trap cleanup EXIT INT TERM

# Start Terminal Server
echo "[terminal] Starting terminal server on port $TERMINAL_PORT..."
TERMINAL_PORT=$TERMINAL_PORT KNOWLEDGE_BASE_PATH=$CONTENT_PATH npx tsx src/server/terminal-server.ts 2>&1 | sed 's/^/[terminal] /' &
TERMINAL_PID=$!

# Start Task Service (from packages/server)
echo "[tasks] Starting task service on port $TASK_SERVICE_PORT..."
cd "$PACKAGES_DIR/server"
TASK_SERVICE_PORT=$TASK_SERVICE_PORT npx tsx src/index.ts 2>&1 | sed 's/^/[tasks] /' &
TASK_PID=$!
cd "$WEB_DIR"

# Give services a moment to start
sleep 1

# Start Next.js
echo "[next] Starting Next.js on port $NEXT_PORT..."
PORT=$NEXT_PORT npx next dev 2>&1 | sed 's/^/[next] /' &
NEXT_PID=$!

# Wait for all processes - if any exits, the script will continue
# Using a loop since macOS bash doesn't support `wait -n`
while true; do
    # Check if any process has died
    if ! kill -0 $TERMINAL_PID 2>/dev/null; then
        echo "[terminal] Terminal server exited"
        break
    fi
    if ! kill -0 $TASK_PID 2>/dev/null; then
        echo "[tasks] Task service exited"
        break
    fi
    if ! kill -0 $NEXT_PID 2>/dev/null; then
        echo "[next] Next.js exited"
        break
    fi
    sleep 1
done

# If we get here, one process died - trigger cleanup
exit 1
