/**
 * Centralized prompt generation for AI-assisted note processing.
 *
 * All prompts generated by the web UI live here as template modules.
 * This enables easy editing, composition, and testing of prompts.
 */

import { CONFIRMATION_INSTRUCTIONS } from "./confirmation";
import { TASK_PATTERN_DETECTION } from "./common/task-patterns";
import { getMeetingPrompt } from "./quick-notes/meeting";
import { getProjectUpdatePrompt } from "./quick-notes/project-update";
import { getTaskPrompt } from "./quick-notes/task";
import { getIdeaPrompt } from "./quick-notes/idea";
import { getGeneralPrompt } from "./quick-notes/general";
import { getBaseInstructions } from "./quick-notes/base";

export interface QuickNote {
  id: string;
  type: "meeting" | "project-update" | "task" | "idea" | "general";
  title: string;
  content: string;
  metadata: Record<string, string>;
  createdAt: string;
}

export interface PromptContext {
  note: QuickNote;
  metadata?: Record<string, unknown>;
}

/**
 * Generate a complete prompt for processing a quick note.
 *
 * Combines:
 * - Base instructions (common to all note types)
 * - Type-specific instructions (meeting, task, etc.)
 * - Task pattern detection (check-in vs new task logic)
 * - Confirmation instructions (AskUserQuestion workflow)
 */
export function generatePrompt(context: PromptContext): string {
  const { note } = context;
  const base = getBaseInstructions(note);
  const typeSpecific = getTypePrompt(note);

  return [base, typeSpecific, TASK_PATTERN_DETECTION, CONFIRMATION_INSTRUCTIONS].join(
    "\n\n"
  );
}

function getTypePrompt(note: QuickNote): string {
  switch (note.type) {
    case "meeting":
      return getMeetingPrompt(note);
    case "project-update":
      return getProjectUpdatePrompt(note);
    case "task":
      return getTaskPrompt(note);
    case "idea":
      return getIdeaPrompt(note);
    case "general":
      return getGeneralPrompt(note);
    default:
      return getGeneralPrompt(note);
  }
}

// Re-export for direct access if needed
export { CONFIRMATION_INSTRUCTIONS } from "./confirmation";
export { TASK_PATTERN_DETECTION } from "./common/task-patterns";
export { FORMAT_INSTRUCTIONS } from "./common/formatting";
